apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-workload-monitoring
  namespace: pf-testing
  labels:
    app: user-workload-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-workload-monitoring
  template:
    metadata:
      name: user-workload-monitoring
      labels:
        app: user-workload-monitoring
    spec:
      containers:
        - name: user-workload-monitoring
          image: ghcr.io/philipfoster/user-workload-monitoring-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
      restartPolicy: Always

