apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: example-monitor
  name: example-monitor
  namespace: pf-testing
spec:
  endpoints:
    - interval: 30s
      port: http
      scheme: http
      path: /actuator/prometheus
  selector:
    matchLabels:
      app: user-workload-monitoring